use anyhow::{Context, Result};
use hf_hub::{BucketTreeEntry, HFClient};
use sha2::{Digest, Sha256};

/// The embedded canonical job script.
pub const EMBEDDED_SPLIT_SCRIPT: &str = include_str!("scripts/split-model-job.sh");
pub const EMBEDDED_CERTIFY_SCRIPT: &str = include_str!("scripts/certify-model-job.sh");

/// Backward-compatible aliases for the split job script.
pub const EMBEDDED_SCRIPT: &str = EMBEDDED_SPLIT_SCRIPT;

// Generated by build.rs — provides embedded script hashes and sizes.
include!(concat!(env!("OUT_DIR"), "/script_hash.rs"));

/// Backward-compatible aliases for the split job script hash.
pub const EMBEDDED_SCRIPT_SHA256: &str = EMBEDDED_SPLIT_SCRIPT_SHA256;
pub const EMBEDDED_SCRIPT_SIZE: u64 = EMBEDDED_SPLIT_SCRIPT_SIZE;

#[derive(Debug, Clone, Copy)]
pub enum JobScript {
    SplitModel,
    CertifyModel,
}

impl JobScript {
    pub fn bucket_path(self) -> &'static str {
        match self {
            Self::SplitModel => "split-model-job.sh",
            Self::CertifyModel => "certify-model-job.sh",
        }
    }

    pub fn embedded(self) -> &'static str {
        match self {
            Self::SplitModel => EMBEDDED_SPLIT_SCRIPT,
            Self::CertifyModel => EMBEDDED_CERTIFY_SCRIPT,
        }
    }

    pub fn expected_sha256(self) -> &'static str {
        match self {
            Self::SplitModel => EMBEDDED_SPLIT_SCRIPT_SHA256,
            Self::CertifyModel => EMBEDDED_CERTIFY_SCRIPT_SHA256,
        }
    }

    pub fn expected_size(self) -> u64 {
        match self {
            Self::SplitModel => EMBEDDED_SPLIT_SCRIPT_SIZE,
            Self::CertifyModel => EMBEDDED_CERTIFY_SCRIPT_SIZE,
        }
    }
}

/// Result of comparing the bucket script against the embedded version.
#[derive(Debug)]
pub struct ScriptFreshness {
    /// Size of the script in the bucket (bytes).
    pub bucket_size: u64,
    /// Size of the embedded script (bytes).
    pub expected_size: u64,
    /// Whether the bucket script matches the embedded version.
    pub is_current: bool,
    /// Human-readable reason when the script is not current.
    pub mismatch_reason: Option<String>,
}

/// Compare the bucket script's size against the embedded version.
///
/// If sizes match, downloads the ~10 KB file and verifies the SHA-256 hash.
pub async fn check_bucket_script(client: &HFClient) -> Result<ScriptFreshness> {
    check_bucket_job_script(client, JobScript::SplitModel).await
}

pub async fn check_bucket_job_script(
    client: &HFClient,
    job_script: JobScript,
) -> Result<ScriptFreshness> {
    let bucket = client.bucket("meshllm", "layer-split-output");
    let bucket_path = job_script.bucket_path();
    let paths = vec![bucket_path.to_string()];

    let entries = bucket
        .get_paths_info(&paths)
        .await
        .context("check bucket script metadata")?;

    let bucket_size = entries
        .into_iter()
        .find_map(|entry| match entry {
            BucketTreeEntry::File { size, .. } => Some(size),
            _ => None,
        })
        .with_context(|| format!("{bucket_path} not found in meshllm/layer-split-output bucket"))?;

    if bucket_size != job_script.expected_size() {
        return Ok(ScriptFreshness {
            bucket_size,
            expected_size: job_script.expected_size(),
            is_current: false,
            mismatch_reason: Some(format!(
                "size differs: bucket has {bucket_size} bytes, embedded script has {expected_size} bytes",
                expected_size = job_script.expected_size()
            )),
        });
    }

    // Sizes match — download to a unique temp file and verify SHA-256.
    let tmp_dir = tempfile::tempdir().context("create bucket script check temp dir")?;
    let tmp_path = tmp_dir.path().join(bucket_path);

    let download_params = hf_hub::BucketDownloadFilesParams {
        files: vec![(bucket_path.to_string(), tmp_path.clone())],
    };

    bucket
        .download_files(&download_params, &Default::default())
        .await
        .context("download bucket script for hash verification")?;

    let bytes = std::fs::read(&tmp_path).context("read downloaded bucket script")?;
    let hash = Sha256::digest(&bytes);
    let hex: String = hash.iter().map(|b| format!("{b:02x}")).collect();

    let is_current = hex == job_script.expected_sha256();

    Ok(ScriptFreshness {
        bucket_size,
        expected_size: job_script.expected_size(),
        is_current,
        mismatch_reason: (!is_current).then(|| {
            format!(
                "sha256 differs: bucket has {hex}, embedded script has {expected}",
                expected = job_script.expected_sha256()
            )
        }),
    })
}

/// Upload the embedded script to the meshllm bucket.
///
/// Requires meshllm org write access.
pub async fn update_bucket_script(client: &HFClient) -> Result<()> {
    update_bucket_job_script(client, JobScript::SplitModel).await
}

pub async fn update_bucket_job_script(client: &HFClient, job_script: JobScript) -> Result<()> {
    let bucket = client.bucket("meshllm", "layer-split-output");
    let bucket_path = job_script.bucket_path();

    // Write embedded script to a unique temp file for upload.
    let tmp_dir = tempfile::tempdir().context("create bucket script upload temp dir")?;
    let tmp_path = tmp_dir.path().join(bucket_path);
    std::fs::write(&tmp_path, job_script.embedded())?;

    let files = vec![(tmp_path.clone(), bucket_path.to_string())];
    bucket
        .upload_files(&files, &Default::default())
        .await
        .context("upload script to meshllm/layer-split-output bucket")?;

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::EMBEDDED_SCRIPT;

    #[test]
    fn embedded_script_prints_mesh_llm_repo_shorthand() {
        assert!(EMBEDDED_SCRIPT.contains(r#"mesh-llm serve --model "${TARGET_REPO}" --split"#));
        assert!(EMBEDDED_SCRIPT.contains("mesh-llm serve --model ${TARGET_REPO} --split"));
        assert!(!EMBEDDED_SCRIPT.contains(r#"mesh-llm serve --model "hf://${TARGET_REPO}""#));
        assert!(!EMBEDDED_SCRIPT.contains("mesh-llm serve --model hf://${TARGET_REPO}"));
    }
}
