use anyhow::{Context, Result};
use hf_hub::{BucketTreeEntry, HFClient};
use sha2::{Digest, Sha256};

/// The embedded canonical job script.
pub const EMBEDDED_SCRIPT: &str = include_str!("scripts/split-model-job.sh");

// Generated by build.rs — provides EMBEDDED_SCRIPT_SHA256 and EMBEDDED_SCRIPT_SIZE.
include!(concat!(env!("OUT_DIR"), "/script_hash.rs"));

/// Result of comparing the bucket script against the embedded version.
#[derive(Debug)]
pub struct ScriptFreshness {
    /// Size of the script in the bucket (bytes).
    pub bucket_size: u64,
    /// Size of the embedded script (bytes).
    pub expected_size: u64,
    /// Whether the bucket script matches the embedded version.
    pub is_current: bool,
    /// Human-readable reason when the script is not current.
    pub mismatch_reason: Option<String>,
}

/// Compare the bucket script's size against the embedded version.
///
/// If sizes match, downloads the ~10 KB file and verifies the SHA-256 hash.
pub async fn check_bucket_script(client: &HFClient) -> Result<ScriptFreshness> {
    let bucket = client.bucket("meshllm", "layer-split-output");
    let paths = vec!["split-model-job.sh".to_string()];

    let entries = bucket
        .get_paths_info(&paths)
        .await
        .context("check bucket script metadata")?;

    let bucket_size = entries
        .into_iter()
        .find_map(|entry| match entry {
            BucketTreeEntry::File { size, .. } => Some(size),
            _ => None,
        })
        .context("split-model-job.sh not found in meshllm/layer-split-output bucket")?;

    if bucket_size != EMBEDDED_SCRIPT_SIZE {
        return Ok(ScriptFreshness {
            bucket_size,
            expected_size: EMBEDDED_SCRIPT_SIZE,
            is_current: false,
            mismatch_reason: Some(format!(
                "size differs: bucket has {bucket_size} bytes, embedded script has {expected_size} bytes",
                expected_size = EMBEDDED_SCRIPT_SIZE
            )),
        });
    }

    // Sizes match — download to a unique temp file and verify SHA-256.
    let tmp_dir = tempfile::tempdir().context("create bucket script check temp dir")?;
    let tmp_path = tmp_dir.path().join("split-model-job.sh");

    let download_params = hf_hub::BucketDownloadFilesParams {
        files: vec![("split-model-job.sh".to_string(), tmp_path.clone())],
    };

    bucket
        .download_files(&download_params, &Default::default())
        .await
        .context("download bucket script for hash verification")?;

    let bytes = std::fs::read(&tmp_path).context("read downloaded bucket script")?;
    let hash = Sha256::digest(&bytes);
    let hex: String = hash.iter().map(|b| format!("{b:02x}")).collect();

    let is_current = hex == EMBEDDED_SCRIPT_SHA256;

    Ok(ScriptFreshness {
        bucket_size,
        expected_size: EMBEDDED_SCRIPT_SIZE,
        is_current,
        mismatch_reason: (!is_current).then(|| {
            format!(
                "sha256 differs: bucket has {hex}, embedded script has {expected}",
                expected = EMBEDDED_SCRIPT_SHA256
            )
        }),
    })
}

/// Upload the embedded script to the meshllm bucket.
///
/// Requires meshllm org write access.
pub async fn update_bucket_script(client: &HFClient) -> Result<()> {
    let bucket = client.bucket("meshllm", "layer-split-output");

    // Write embedded script to a unique temp file for upload.
    let tmp_dir = tempfile::tempdir().context("create bucket script upload temp dir")?;
    let tmp_path = tmp_dir.path().join("split-model-job.sh");
    std::fs::write(&tmp_path, EMBEDDED_SCRIPT)?;

    let files = vec![(tmp_path.clone(), "split-model-job.sh".to_string())];
    bucket
        .upload_files(&files, &Default::default())
        .await
        .context("upload script to meshllm/layer-split-output bucket")?;

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::EMBEDDED_SCRIPT;

    #[test]
    fn embedded_script_prints_mesh_llm_repo_shorthand() {
        assert!(EMBEDDED_SCRIPT.contains(r#"mesh-llm serve --model "${TARGET_REPO}" --split"#));
        assert!(EMBEDDED_SCRIPT.contains("mesh-llm serve --model ${TARGET_REPO} --split"));
        assert!(!EMBEDDED_SCRIPT.contains(r#"mesh-llm serve --model "hf://${TARGET_REPO}""#));
        assert!(!EMBEDDED_SCRIPT.contains("mesh-llm serve --model hf://${TARGET_REPO}"));
    }
}
