//! Model download with resume support using reqwest.

use anyhow::{Context, Result};
use std::path::{Path, PathBuf};
use tokio::io::AsyncWriteExt;

pub struct CatalogModel {
    pub name: &'static str,
    pub file: &'static str,
    pub url: &'static str,
    pub size: &'static str,
    pub description: &'static str,
    /// If set, this model has a recommended draft model for speculative decoding.
    pub draft: Option<&'static str>,
    /// MoE expert routing config. If set, this model supports expert sharding.
    /// Pre-computed from `moe-analyze --export-ranking --all-layers`.
    pub moe: Option<MoeConfig>,
    /// Additional split GGUF files (for models too large for a single file).
    /// Each entry is (filename, url). llama.cpp auto-discovers splits from the
    /// first file, but all parts must be present in the same directory.
    pub extra_files: &'static [(&'static str, &'static str)],
    /// Exploded MoE expert repo: HuggingFace base URL for per-expert files.
    /// Contains trunk.gguf + expert-NNN.gguf. Enables partial downloads where
    /// each node fetches only its assigned experts instead of the full model.
    pub exploded_repo: Option<&'static str>,
}

/// Pre-computed MoE expert sharding configuration for a model.
/// Derived from router gate mass analysis — determines which experts go where.
#[derive(Clone, Debug)]
pub struct MoeConfig {
    /// Total number of experts in the model
    pub n_expert: u32,
    /// Number of experts selected per token (top-k)
    pub n_expert_used: u32,
    /// Minimum number of experts per node for coherent output.
    /// Determined experimentally per model (~36% for Qwen3-30B-A3B).
    pub min_experts_per_node: u32,
    /// Expert IDs sorted by gate mass descending (hottest first).
    /// This is the content of the ranking CSV, embedded directly.
    pub ranking: &'static [u32],

}

// Pre-computed expert rankings by gate mass (hottest first).
// Generated by: llama-moe-analyze --export-ranking --all-layers
// These are a property of the model weights — compute once, embed forever.

#[rustfmt::skip]
static QWEN3_30B_A3B_RANKING: &[u32] = &[
    0, 26, 41, 69, 104, 70, 81, 89, 7, 21, 105, 75, 8, 78, 82, 5, 115, 16, 59, 32,
    111, 38, 103, 49, 51, 73, 96, 85, 18, 71, 68, 2, 47, 37, 58, 24, 110, 57, 65, 98,
    14, 80, 52, 112, 113, 36, 84, 9, 30, 28, 66, 122, 50, 92, 1, 10, 3, 91, 56, 117,
    87, 17, 64, 34, 25, 94, 33, 86, 102, 74, 120, 31, 4, 45, 13, 61, 99, 93, 107, 46,
    48, 55, 35, 12, 22, 124, 29, 27, 53, 44, 6, 39, 123, 116, 101, 126, 62, 127, 106, 97,
    63, 72, 109, 42, 125, 20, 76, 43, 121, 90, 100, 77, 23, 119, 83, 11, 54, 19, 114, 79,
    108, 40, 67, 88, 60, 95, 118, 15,
];

pub const MODEL_CATALOG: &[CatalogModel] = &[
    // ── Tiny (≤3GB VRAM) ────────────────────────────────────────────
    CatalogModel {
        name: "Qwen3-4B-Q4_K_M",
        file: "Qwen3-4B-Q4_K_M.gguf",
        url: "https://huggingface.co/unsloth/Qwen3-4B-GGUF/resolve/main/Qwen3-4B-Q4_K_M.gguf",
        size: "2.5GB",
        description: "Qwen3 starter, thinking/non-thinking modes",
        draft: Some("Qwen3-0.6B-Q4_K_M"),
        moe: None,
        extra_files: &[],
        exploded_repo: None,
    },
    CatalogModel {
        name: "Qwen2.5-3B-Instruct-Q4_K_M",
        file: "Qwen2.5-3B-Instruct-Q4_K_M.gguf",
        url: "https://huggingface.co/Qwen/Qwen2.5-3B-Instruct-GGUF/resolve/main/qwen2.5-3b-instruct-q4_k_m.gguf",
        size: "2.1GB",
        description: "Small & fast general chat",
        draft: Some("Qwen2.5-0.5B-Instruct-Q4_K_M"),
        moe: None,
        extra_files: &[],
        exploded_repo: None,
    },
    CatalogModel {
        name: "Llama-3.2-3B-Instruct-Q4_K_M",
        file: "Llama-3.2-3B-Instruct-Q4_K_M.gguf",
        url: "https://huggingface.co/bartowski/Llama-3.2-3B-Instruct-GGUF/resolve/main/Llama-3.2-3B-Instruct-Q4_K_M.gguf",
        size: "2.0GB",
        description: "Meta Llama 3.2, goose default, good tool calling",
        draft: Some("Llama-3.2-1B-Instruct-Q4_K_M"),
        moe: None,
        extra_files: &[],
        exploded_repo: None,
    },
    // ── Small (6-8GB VRAM) ──────────────────────────────────────────
    CatalogModel {
        name: "Qwen3-8B-Q4_K_M",
        file: "Qwen3-8B-Q4_K_M.gguf",
        url: "https://huggingface.co/unsloth/Qwen3-8B-GGUF/resolve/main/Qwen3-8B-Q4_K_M.gguf",
        size: "5.0GB",
        description: "Qwen3 mid-tier, strong for its size",
        draft: Some("Qwen3-0.6B-Q4_K_M"),
        moe: None,
        extra_files: &[],
        exploded_repo: None,
    },
    CatalogModel {
        name: "Qwen2.5-Coder-7B-Instruct-Q4_K_M",
        file: "Qwen2.5-Coder-7B-Instruct-Q4_K_M.gguf",
        url: "https://huggingface.co/Qwen/Qwen2.5-Coder-7B-Instruct-GGUF/resolve/main/qwen2.5-coder-7b-instruct-q4_k_m.gguf",
        size: "4.4GB",
        description: "Code generation & completion",
        draft: Some("Qwen2.5-0.5B-Instruct-Q4_K_M"),
        moe: None,
        extra_files: &[],
        exploded_repo: None,
    },
    CatalogModel {
        name: "Gemma-3-12B-it-Q4_K_M",
        file: "Gemma-3-12B-it-Q4_K_M.gguf",
        url: "https://huggingface.co/unsloth/gemma-3-12b-it-GGUF/resolve/main/gemma-3-12b-it-Q4_K_M.gguf",
        size: "7.3GB",
        description: "Google Gemma 3 12B, punches above weight",
        draft: Some("Gemma-3-1B-it-Q4_K_M"),
        moe: None,
        extra_files: &[],
        exploded_repo: None,
    },
    CatalogModel {
        name: "Hermes-2-Pro-Mistral-7B-Q4_K_M",
        file: "Hermes-2-Pro-Mistral-7B-Q4_K_M.gguf",
        url: "https://huggingface.co/bartowski/Hermes-2-Pro-Mistral-7B-GGUF/resolve/main/Hermes-2-Pro-Mistral-7B-Q4_K_M.gguf",
        size: "4.4GB",
        description: "Goose default, strong tool calling for agents",
        draft: None,
        moe: None,
        extra_files: &[],
        exploded_repo: None,
    },
    // ── Medium (11-17GB VRAM) ───────────────────────────────────────
    CatalogModel {
        name: "Qwen3-14B-Q4_K_M",
        file: "Qwen3-14B-Q4_K_M.gguf",
        url: "https://huggingface.co/unsloth/Qwen3-14B-GGUF/resolve/main/Qwen3-14B-Q4_K_M.gguf",
        size: "9.0GB",
        description: "Qwen3 strong chat, thinking modes",
        draft: Some("Qwen3-0.6B-Q4_K_M"),
        moe: None,
        extra_files: &[],
        exploded_repo: None,
    },
    CatalogModel {
        name: "Qwen2.5-14B-Instruct-Q4_K_M",
        file: "Qwen2.5-14B-Instruct-Q4_K_M.gguf",
        url: "https://huggingface.co/bartowski/Qwen2.5-14B-Instruct-GGUF/resolve/main/Qwen2.5-14B-Instruct-Q4_K_M.gguf",
        size: "9.0GB",
        description: "Solid general chat",
        draft: Some("Qwen2.5-0.5B-Instruct-Q4_K_M"),
        moe: None,
        extra_files: &[],
        exploded_repo: None,
    },
    CatalogModel {
        name: "Qwen2.5-Coder-14B-Instruct-Q4_K_M",
        file: "Qwen2.5-Coder-14B-Instruct-Q4_K_M.gguf",
        url: "https://huggingface.co/bartowski/Qwen2.5-Coder-14B-Instruct-GGUF/resolve/main/Qwen2.5-Coder-14B-Instruct-Q4_K_M.gguf",
        size: "9.0GB",
        description: "Strong code gen, fills gap between 7B and 32B",
        draft: Some("Qwen2.5-0.5B-Instruct-Q4_K_M"),
        moe: None,
        extra_files: &[],
        exploded_repo: None,
    },
    CatalogModel {
        name: "DeepSeek-R1-Distill-Qwen-14B-Q4_K_M",
        file: "DeepSeek-R1-Distill-Qwen-14B-Q4_K_M.gguf",
        url: "https://huggingface.co/unsloth/DeepSeek-R1-Distill-Qwen-14B-GGUF/resolve/main/DeepSeek-R1-Distill-Qwen-14B-Q4_K_M.gguf",
        size: "9.0GB",
        description: "DeepSeek R1 reasoning distilled into Qwen 14B",
        draft: Some("Qwen2.5-0.5B-Instruct-Q4_K_M"),
        moe: None,
        extra_files: &[],
        exploded_repo: None,
    },
    CatalogModel {
        name: "Devstral-Small-2505-Q4_K_M",
        file: "Devstral-Small-2505-Q4_K_M.gguf",
        url: "https://huggingface.co/unsloth/Devstral-Small-2505-GGUF/resolve/main/Devstral-Small-2505-Q4_K_M.gguf",
        size: "14.3GB",
        description: "Mistral agentic coding, tool use",
        draft: None,
        moe: None,
        extra_files: &[],
        exploded_repo: None,
    },
    CatalogModel {
        name: "Mistral-Small-3.1-24B-Instruct-Q4_K_M",
        file: "Mistral-Small-3.1-24B-Instruct-2503-Q4_K_M.gguf",
        url: "https://huggingface.co/unsloth/Mistral-Small-3.1-24B-Instruct-2503-GGUF/resolve/main/Mistral-Small-3.1-24B-Instruct-2503-Q4_K_M.gguf",
        size: "14.3GB",
        description: "Mistral general chat, good tool calling",
        draft: None,
        moe: None,
        extra_files: &[],
        exploded_repo: None,
    },
    // ── Large (20-24GB VRAM) ────────────────────────────────────────
    CatalogModel {
        name: "GLM-4.7-Flash-Q4_K_M",
        file: "GLM-4.7-Flash-Q4_K_M.gguf",
        url: "https://huggingface.co/unsloth/GLM-4.7-Flash-GGUF/resolve/main/GLM-4.7-Flash-Q4_K_M.gguf",
        size: "18GB",
        description: "MoE 30B/3B active, 64 experts top-4, fast inference, tool calling",
        draft: None,
        moe: Some(MoeConfig {
            n_expert: 64,
            n_expert_used: 4,
            min_experts_per_node: 24,
            ranking: &[], // no pre-baked ranking — uses GGUF auto-detect + fallback
        }),
        extra_files: &[],
        exploded_repo: None,
    },
    CatalogModel {
        name: "Qwen3-30B-A3B-Q4_K_M",
        file: "Qwen3-30B-A3B-Q4_K_M.gguf",
        url: "https://huggingface.co/unsloth/Qwen3-30B-A3B-GGUF/resolve/main/Qwen3-30B-A3B-Q4_K_M.gguf",
        size: "17.3GB",
        description: "MoE general chat, 128 experts top-8, thinking/non-thinking",
        draft: Some("Qwen3-0.6B-Q4_K_M"),
        moe: Some(MoeConfig {
            n_expert: 128,
            n_expert_used: 8,
            min_experts_per_node: 46,
            ranking: QWEN3_30B_A3B_RANKING, // same arch as Coder variant
        }),
        extra_files: &[],
        exploded_repo: Some("https://huggingface.co/michaelneale/Qwen3-30B-A3B-Q4_K_M-exploded/resolve/main"),
    },
    CatalogModel {
        name: "Qwen3-Coder-30B-A3B-Instruct-Q4_K_M",
        file: "Qwen3-Coder-30B-A3B-Instruct-Q4_K_M.gguf",
        url: "https://huggingface.co/unsloth/Qwen3-Coder-30B-A3B-Instruct-GGUF/resolve/main/Qwen3-Coder-30B-A3B-Instruct-Q4_K_M.gguf",
        size: "18.6GB",
        description: "MoE agentic coding, tool use, 128 experts top-8",
        draft: Some("Qwen3-0.6B-Q4_K_M"),
        moe: Some(MoeConfig {
            n_expert: 128,
            n_expert_used: 8,
            min_experts_per_node: 46,
            ranking: QWEN3_30B_A3B_RANKING, // same arch as Qwen3-30B-A3B
        }),
        extra_files: &[],
        exploded_repo: None,
    },
    CatalogModel {
        name: "GLM-4-32B-0414-Q4_K_M",
        file: "GLM-4-32B-0414-Q4_K_M.gguf",
        url: "https://huggingface.co/unsloth/GLM-4-32B-0414-GGUF/resolve/main/GLM-4-32B-0414-Q4_K_M.gguf",
        size: "19.7GB",
        description: "Strong 32B, good tool calling",
        draft: None,
        moe: None,
        extra_files: &[],
        exploded_repo: None,
    },
    CatalogModel {
        name: "Qwen3-32B-Q4_K_M",
        file: "Qwen3-32B-Q4_K_M.gguf",
        url: "https://huggingface.co/unsloth/Qwen3-32B-GGUF/resolve/main/Qwen3-32B-Q4_K_M.gguf",
        size: "19.8GB",
        description: "Best Qwen3 dense, thinking/non-thinking modes",
        draft: Some("Qwen3-0.6B-Q4_K_M"),
        moe: None,
        extra_files: &[],
        exploded_repo: None,
    },
    CatalogModel {
        name: "DeepSeek-R1-Distill-Qwen-32B-Q4_K_M",
        file: "DeepSeek-R1-Distill-Qwen-32B-Q4_K_M.gguf",
        url: "https://huggingface.co/unsloth/DeepSeek-R1-Distill-Qwen-32B-GGUF/resolve/main/DeepSeek-R1-Distill-Qwen-32B-Q4_K_M.gguf",
        size: "19.9GB",
        description: "DeepSeek R1 reasoning distilled into Qwen 32B",
        draft: Some("Qwen2.5-0.5B-Instruct-Q4_K_M"),
        moe: None,
        extra_files: &[],
        exploded_repo: None,
    },
    CatalogModel {
        name: "Qwen2.5-32B-Instruct-Q4_K_M",
        file: "Qwen2.5-32B-Instruct-Q4_K_M.gguf",
        url: "https://huggingface.co/bartowski/Qwen2.5-32B-Instruct-GGUF/resolve/main/Qwen2.5-32B-Instruct-Q4_K_M.gguf",
        size: "20GB",
        description: "Proven general chat",
        draft: Some("Qwen2.5-0.5B-Instruct-Q4_K_M"),
        moe: None,
        extra_files: &[],
        exploded_repo: None,
    },
    CatalogModel {
        name: "Qwen2.5-Coder-32B-Instruct-Q4_K_M",
        file: "Qwen2.5-Coder-32B-Instruct-Q4_K_M.gguf",
        url: "https://huggingface.co/Qwen/Qwen2.5-Coder-32B-Instruct-GGUF/resolve/main/qwen2.5-coder-32b-instruct-q4_k_m.gguf",
        size: "20GB",
        description: "Top-tier code gen, matches GPT-4o on code",
        draft: Some("Qwen2.5-0.5B-Instruct-Q4_K_M"),
        moe: None,
        extra_files: &[],
        exploded_repo: None,
    },
    CatalogModel {
        name: "Llama-4-Scout-Q4_K_M",
        file: "Llama-4-Scout-4bit-Q4_K_M.gguf",
        url: "https://huggingface.co/glogwa68/Llama-4-scout-GGUF/resolve/main/Llama-4-Scout-4bit-Q4_K_M.gguf",
        size: "22.5GB",
        description: "MoE 109B/17B active, 16 experts top-1, Meta latest, tool calling",
        draft: None,
        moe: Some(MoeConfig {
            n_expert: 16,
            n_expert_used: 1,
            min_experts_per_node: 6,
            ranking: &[], // no pre-baked ranking — uses GGUF auto-detect
        }),
        extra_files: &[],
        exploded_repo: None,
    },
    CatalogModel {
        name: "Gemma-3-27B-it-Q4_K_M",
        file: "Gemma-3-27B-it-Q4_K_M.gguf",
        url: "https://huggingface.co/bartowski/google_gemma-3-27b-it-GGUF/resolve/main/google_gemma-3-27b-it-Q4_K_M.gguf",
        size: "17GB",
        description: "Google Gemma 3 27B, strong reasoning",
        draft: Some("Gemma-3-1B-it-Q4_K_M"),
        moe: None,
        extra_files: &[],
        exploded_repo: None,
    },
    // ── XL (48-53GB VRAM, tensor split candidates) ──────────────────
    CatalogModel {
        name: "Llama-3.3-70B-Instruct-Q4_K_M",
        file: "Llama-3.3-70B-Instruct-Q4_K_M.gguf",
        url: "https://huggingface.co/bartowski/Llama-3.3-70B-Instruct-GGUF/resolve/main/Llama-3.3-70B-Instruct-Q4_K_M.gguf",
        size: "42.5GB",
        description: "Meta Llama 3.3 70B, strong all-around",
        draft: Some("Llama-3.2-1B-Instruct-Q4_K_M"),
        moe: None,
        extra_files: &[],
        exploded_repo: None,
    },
    CatalogModel {
        name: "Qwen2.5-72B-Instruct-Q4_K_M",
        file: "Qwen2.5-72B-Instruct-Q4_K_M.gguf",
        url: "https://huggingface.co/bartowski/Qwen2.5-72B-Instruct-GGUF/resolve/main/Qwen2.5-72B-Instruct-Q4_K_M.gguf",
        size: "47.4GB",
        description: "Flagship Qwen2.5, great tensor split showcase",
        draft: Some("Qwen2.5-0.5B-Instruct-Q4_K_M"),
        moe: None,
        extra_files: &[],
        exploded_repo: None,
    },
    // ── XXL (100GB+ VRAM, split GGUF) ─────────────────────────────
    CatalogModel {
        name: "GLM-5-UD-IQ2_XXS",
        file: "GLM-5-UD-IQ2_XXS-00001-of-00006.gguf",
        url: "https://huggingface.co/unsloth/GLM-5-GGUF/resolve/main/UD-IQ2_XXS/GLM-5-UD-IQ2_XXS-00001-of-00006.gguf",
        size: "224GB",
        description: "GLM-5 MoE 300B/24B active, 256 experts top-8, ultra-quantised IQ2_XXS",
        draft: None,
        moe: Some(MoeConfig {
            n_expert: 256,
            n_expert_used: 8,
            min_experts_per_node: 96,
            ranking: &[],
        }),
        extra_files: &[
            ("GLM-5-UD-IQ2_XXS-00002-of-00006.gguf", "https://huggingface.co/unsloth/GLM-5-GGUF/resolve/main/UD-IQ2_XXS/GLM-5-UD-IQ2_XXS-00002-of-00006.gguf"),
            ("GLM-5-UD-IQ2_XXS-00003-of-00006.gguf", "https://huggingface.co/unsloth/GLM-5-GGUF/resolve/main/UD-IQ2_XXS/GLM-5-UD-IQ2_XXS-00003-of-00006.gguf"),
            ("GLM-5-UD-IQ2_XXS-00004-of-00006.gguf", "https://huggingface.co/unsloth/GLM-5-GGUF/resolve/main/UD-IQ2_XXS/GLM-5-UD-IQ2_XXS-00004-of-00006.gguf"),
            ("GLM-5-UD-IQ2_XXS-00005-of-00006.gguf", "https://huggingface.co/unsloth/GLM-5-GGUF/resolve/main/UD-IQ2_XXS/GLM-5-UD-IQ2_XXS-00005-of-00006.gguf"),
            ("GLM-5-UD-IQ2_XXS-00006-of-00006.gguf", "https://huggingface.co/unsloth/GLM-5-GGUF/resolve/main/UD-IQ2_XXS/GLM-5-UD-IQ2_XXS-00006-of-00006.gguf"),
        ],
        exploded_repo: None,
    },
    // ── Draft models ────────────────────────────────────────────────
    CatalogModel {
        name: "Qwen2.5-0.5B-Instruct-Q4_K_M",
        file: "Qwen2.5-0.5B-Instruct-Q4_K_M.gguf",
        url: "https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct-GGUF/resolve/main/qwen2.5-0.5b-instruct-q4_k_m.gguf",
        size: "491MB",
        description: "Draft for Qwen2.5 and DeepSeek-R1-Distill models",
        draft: None,
        moe: None,
        extra_files: &[],
        exploded_repo: None,
    },
    CatalogModel {
        name: "Qwen3-0.6B-Q4_K_M",
        file: "Qwen3-0.6B-Q4_K_M.gguf",
        url: "https://huggingface.co/unsloth/Qwen3-0.6B-GGUF/resolve/main/Qwen3-0.6B-Q4_K_M.gguf",
        size: "397MB",
        description: "Draft for Qwen3 models",
        draft: None,
        moe: None,
        extra_files: &[],
        exploded_repo: None,
    },
    CatalogModel {
        name: "Llama-3.2-1B-Instruct-Q4_K_M",
        file: "Llama-3.2-1B-Instruct-Q4_K_M.gguf",
        url: "https://huggingface.co/bartowski/Llama-3.2-1B-Instruct-GGUF/resolve/main/Llama-3.2-1B-Instruct-Q4_K_M.gguf",
        size: "760MB",
        description: "Draft for Llama 3.x and Llama 4 models",
        draft: None,
        moe: None,
        extra_files: &[],
        exploded_repo: None,
    },
    CatalogModel {
        name: "Gemma-3-1B-it-Q4_K_M",
        file: "Gemma-3-1B-it-Q4_K_M.gguf",
        url: "https://huggingface.co/bartowski/google_gemma-3-1b-it-GGUF/resolve/main/google_gemma-3-1b-it-Q4_K_M.gguf",
        size: "780MB",
        description: "Draft for Gemma 3 models",
        draft: None,
        moe: None,
        extra_files: &[],
        exploded_repo: None,
    },
];

/// Get the models directory (~/.models/)
pub fn models_dir() -> PathBuf {
    dirs::home_dir()
        .unwrap_or_else(|| PathBuf::from("."))
        .join(".models")
}

/// Find a catalog model by name (case-insensitive partial match)
/// Parse a size string like "20GB", "4.4GB", "491MB" into GB as f64.
pub fn parse_size_gb(s: &str) -> f64 {
    let s = s.trim();
    if let Some(gb) = s.strip_suffix("GB") {
        gb.trim().parse().unwrap_or(0.0)
    } else if let Some(mb) = s.strip_suffix("MB") {
        mb.trim().parse::<f64>().unwrap_or(0.0) / 1000.0
    } else {
        0.0
    }
}

pub fn find_model(query: &str) -> Option<&'static CatalogModel> {
    let q = query.to_lowercase();
    MODEL_CATALOG
        .iter()
        .find(|m| m.name.to_lowercase() == q)
        .or_else(|| {
            MODEL_CATALOG
                .iter()
                .find(|m| m.name.to_lowercase().contains(&q))
        })
}

/// Download a model to ~/.models/ with resume support.
/// Returns the path to the primary downloaded file.
/// For split GGUFs (extra_files), downloads all parts to the same directory.
pub async fn download_model(model: &CatalogModel) -> Result<PathBuf> {
    let dir = models_dir();
    tokio::fs::create_dir_all(&dir).await?;
    let dest = dir.join(model.file);

    // Collect all files to download: primary + extra splits
    let mut files: Vec<(&str, &str)> = vec![(model.file, model.url)];
    for (f, u) in model.extra_files {
        files.push((f, u));
    }

    let mut all_present = true;
    let mut total_size: u64 = 0;
    for (file, _) in &files {
        let path = dir.join(file);
        let size = tokio::fs::metadata(&path).await.map(|m| m.len()).unwrap_or(0);
        if size < 1_000_000 {
            all_present = false;
            break;
        }
        total_size += size;
    }

    if all_present {
        eprintln!(
            "✅ {} already exists ({:.1}GB, {} file{})",
            model.name,
            total_size as f64 / 1e9,
            files.len(),
            if files.len() > 1 { "s" } else { "" },
        );
        return Ok(dest);
    }

    eprintln!("📥 Downloading {} ({})...", model.name, model.size);

    // Collect files that still need downloading
    let mut needed: Vec<(String, String)> = Vec::new();
    for (file, url) in &files {
        let path = dir.join(file);
        if path.exists() {
            let size = tokio::fs::metadata(&path).await.map(|m| m.len()).unwrap_or(0);
            if size > 1_000_000 {
                eprintln!("  ✅ {file} already exists ({:.1}GB)", size as f64 / 1e9);
                continue;
            }
        }
        needed.push((file.to_string(), url.to_string()));
    }

    if needed.len() > 1 {
        // Parallel download of split files
        eprintln!("  ⚡ Downloading {} files in parallel...", needed.len());
        let total = needed.len();
        let completed = std::sync::Arc::new(std::sync::atomic::AtomicUsize::new(0));
        let mut handles = Vec::new();
        for (file, url) in needed {
            let path = dir.join(&file);
            let completed = completed.clone();
            handles.push(tokio::spawn(async move {
                download_with_resume(&path, &url).await?;
                let done = completed.fetch_add(1, std::sync::atomic::Ordering::Relaxed) + 1;
                eprintln!("  ✅ {file} [{done}/{total}]");
                Ok::<(), anyhow::Error>(())
            }));
        }
        for handle in handles {
            handle.await??;
        }
    } else if let Some((file, url)) = needed.into_iter().next() {
        // Single file — just download it
        let path = dir.join(&file);
        download_with_resume(&path, &url).await?;
    }

    eprintln!("✅ Downloaded {} to {}", model.name, dir.display());
    Ok(dest)
}

/// Download an exploded MoE shard: trunk + assigned expert files from HF repo.
///
/// - `repo_base`: HF base URL (e.g. `https://huggingface.co/.../resolve/main`)
/// - `expert_ids`: which expert files to download (from compute_assignments)
/// - `model_name`: used for the local directory name
///
/// Downloads to `~/.models/exploded/<model_name>/trunk.gguf` + `expert-NNN.gguf`.
/// Returns the directory path containing the downloaded files.
pub async fn download_exploded_experts(
    repo_base: &str,
    expert_ids: &[u32],
    model_name: &str,
) -> Result<PathBuf> {
    let dir = models_dir().join("exploded").join(model_name);
    tokio::fs::create_dir_all(&dir).await?;

    // Download trunk
    let trunk_path = dir.join("trunk.gguf");
    let trunk_url = format!("{repo_base}/trunk.gguf");
    if trunk_path.exists() {
        let size = tokio::fs::metadata(&trunk_path).await.map(|m| m.len()).unwrap_or(0);
        if size > 1_000_000 {
            eprintln!("  ✅ trunk.gguf already exists ({:.1}GB)", size as f64 / 1e9);
        } else {
            eprintln!("  📥 trunk.gguf...");
            download_with_resume(&trunk_path, &trunk_url).await?;
        }
    } else {
        eprintln!("  📥 trunk.gguf...");
        download_with_resume(&trunk_path, &trunk_url).await?;
    }

    // Download assigned expert files
    for (i, &eid) in expert_ids.iter().enumerate() {
        let fname = format!("expert-{:03}.gguf", eid);
        let expert_path = dir.join(&fname);
        let expert_url = format!("{repo_base}/{fname}");

        if expert_path.exists() {
            let size = tokio::fs::metadata(&expert_path).await.map(|m| m.len()).unwrap_or(0);
            if size > 1_000_000 {
                continue; // already have it
            }
        }
        eprintln!("  📥 [{}/{}] {fname}...", i + 1, expert_ids.len());
        download_with_resume(&expert_path, &expert_url).await?;
    }

    let trunk_size = tokio::fs::metadata(&trunk_path).await.map(|m| m.len()).unwrap_or(0);
    eprintln!("✅ Exploded shard ready: trunk ({:.1}GB) + {} experts in {}",
        trunk_size as f64 / 1e9, expert_ids.len(), dir.display());
    Ok(dir)
}

/// Assemble a shard GGUF from exploded expert files.
///
/// Assemble a shard GGUF from trunk + expert files using the Rust assembler.
///
/// - `exploded_dir`: directory with trunk.gguf + expert-NNN.gguf files
/// - `expert_ids`: which experts to include (must exist in exploded_dir)
/// - `output_path`: where to write the assembled shard GGUF
pub fn assemble_shard(
    exploded_dir: &Path,
    expert_ids: &[u32],
    output_path: &Path,
) -> Result<()> {
    let trunk = exploded_dir.join("trunk.gguf");
    let expert_paths: Vec<PathBuf> = expert_ids.iter()
        .map(|&eid| exploded_dir.join(format!("expert-{:03}.gguf", eid)))
        .collect();

    crate::moe::assemble_shard(&trunk, &expert_paths, output_path)
}

/// Path to a cached assembled shard for exploded models.
pub fn exploded_shard_path(model_name: &str, n_nodes: usize, node_index: usize) -> PathBuf {
    models_dir()
        .join("exploded")
        .join(model_name)
        .join("shards")
        .join(format!("{n_nodes}-nodes"))
        .join(format!("node-{node_index}.gguf"))
}

/// Download any URL to a destination path with resume support.
pub async fn download_url(url: &str, dest: &Path) -> Result<()> {
    download_with_resume(dest, url).await
}

/// Download with resume support and retries using reqwest.
async fn download_with_resume(dest: &Path, url: &str) -> Result<()> {
    use tokio_stream::StreamExt;

    let tmp = dest.with_extension("gguf.part");
    let client = reqwest::Client::builder()
        .timeout(std::time::Duration::from_secs(3600)) // 1h overall timeout
        .connect_timeout(std::time::Duration::from_secs(30))
        .build()?;

    for attempt in 1..=5 {
        // Check how much we already have (for resume)
        let existing_bytes = if tmp.exists() {
            tokio::fs::metadata(&tmp).await?.len()
        } else {
            0
        };

        eprintln!(
            "  attempt {attempt}/5{}...",
            if existing_bytes > 0 {
                format!(" (resuming from {:.1}MB)", existing_bytes as f64 / 1e6)
            } else {
                String::new()
            }
        );

        let mut request = client.get(url);
        if existing_bytes > 0 {
            request = request.header("Range", format!("bytes={existing_bytes}-"));
        }

        let response = match request.send().await {
            Ok(r) => r,
            Err(e) => {
                eprintln!("  connection failed: {e}");
                if attempt < 5 {
                    eprintln!("  retrying in 3s...");
                    tokio::time::sleep(std::time::Duration::from_secs(3)).await;
                }
                continue;
            }
        };

        let status = response.status();
        if !status.is_success() && status != reqwest::StatusCode::PARTIAL_CONTENT {
            // If server doesn't support resume (416 Range Not Satisfiable), start fresh
            if status == reqwest::StatusCode::RANGE_NOT_SATISFIABLE {
                let _ = tokio::fs::remove_file(&tmp).await;
                eprintln!("  server rejected resume, starting fresh...");
                continue;
            }
            anyhow::bail!("HTTP {status} downloading {url}");
        }

        // Total size from Content-Length (or Content-Range)
        let total_bytes = if status == reqwest::StatusCode::PARTIAL_CONTENT {
            // Content-Range: bytes 1234-5678/9999
            response
                .headers()
                .get("content-range")
                .and_then(|v| v.to_str().ok())
                .and_then(|s| s.rsplit('/').next())
                .and_then(|s| s.parse::<u64>().ok())
        } else {
            response.content_length().map(|cl| cl + existing_bytes)
        };

        // Open file for append (resume) or create
        let mut file = tokio::fs::OpenOptions::new()
            .create(true)
            .append(true)
            .open(&tmp)
            .await
            .context("Failed to open temp file")?;

        let mut stream = response.bytes_stream();
        let mut downloaded = existing_bytes;
        let mut last_progress = std::time::Instant::now();

        // Print initial progress
        print_progress(downloaded, total_bytes);

        loop {
            match stream.next().await {
                Some(Ok(chunk)) => {
                    file.write_all(&chunk)
                        .await
                        .context("Failed to write chunk")?;
                    downloaded += chunk.len() as u64;

                    // Update progress every 500ms
                    if last_progress.elapsed() >= std::time::Duration::from_millis(500) {
                        print_progress(downloaded, total_bytes);
                        last_progress = std::time::Instant::now();
                    }
                }
                Some(Err(e)) => {
                    file.flush().await.ok();
                    eprint!("\r");
                    eprintln!(
                        "  download interrupted at {:.1}MB: {e}",
                        downloaded as f64 / 1e6
                    );
                    if attempt < 5 {
                        eprintln!("  retrying in 3s (will resume)...");
                        tokio::time::sleep(std::time::Duration::from_secs(3)).await;
                    }
                    break;
                }
                None => {
                    // Stream complete
                    file.flush().await?;
                    eprint!("\r");
                    print_progress(downloaded, total_bytes);
                    eprintln!();
                    tokio::fs::rename(&tmp, dest)
                        .await
                        .context("Failed to move downloaded file")?;
                    return Ok(());
                }
            }
        }
    }

    // Clean up partial on total failure
    let _ = tokio::fs::remove_file(&tmp).await;
    anyhow::bail!("Download failed after 5 attempts");
}

fn print_progress(downloaded: u64, total: Option<u64>) {
    if let Some(total) = total {
        let pct = (downloaded as f64 / total as f64) * 100.0;
        let downloaded_mb = downloaded as f64 / 1e6;
        let total_mb = total as f64 / 1e6;
        eprint!("\r  {:.1}/{:.1}MB ({:.1}%)", downloaded_mb, total_mb, pct);
    } else {
        eprint!("\r  {:.1}MB", downloaded as f64 / 1e6);
    }
}

/// List available models
pub fn list_models() {
    eprintln!("Available models:");
    eprintln!();
    for m in MODEL_CATALOG {
        let draft_info = if let Some(d) = m.draft {
            format!(" (draft: {})", d)
        } else {
            String::new()
        };
        eprintln!(
            "  {:40} {:>6}  {}{}",
            m.name, m.size, m.description, draft_info
        );
    }
}
