//! Model download with resume support using reqwest.

use anyhow::{Context, Result};
use std::path::{Path, PathBuf};
use tokio::io::AsyncWriteExt;

pub struct CatalogModel {
    pub name: &'static str,
    pub file: &'static str,
    pub url: &'static str,
    pub size: &'static str,
    pub description: &'static str,
    /// If set, this model has a recommended draft model for speculative decoding.
    pub draft: Option<&'static str>,
    /// MoE expert routing config. If set, this model supports expert sharding.
    /// Pre-computed from `moe-analyze --export-ranking --all-layers`.
    pub moe: Option<MoeConfig>,
    /// Additional split GGUF files (for models too large for a single file).
    /// Each entry is (filename, url). llama.cpp auto-discovers splits from the
    /// first file, but all parts must be present in the same directory.
    pub extra_files: &'static [(&'static str, &'static str)],
    /// Multimodal projector for vision models (filename, url).
    /// When set, llama-server is launched with `--mmproj <file>`.
    pub mmproj: Option<(&'static str, &'static str)>,
}

/// Pre-computed MoE expert sharding configuration for a model.
/// Derived from router gate mass analysis — determines which experts go where.
#[derive(Clone, Debug)]
pub struct MoeConfig {
    /// Total number of experts in the model
    pub n_expert: u32,
    /// Number of experts selected per token (top-k)
    pub n_expert_used: u32,
    /// Minimum number of experts per node for coherent output.
    /// Determined experimentally per model (~36% for Qwen3-30B-A3B).
    pub min_experts_per_node: u32,
    /// Expert IDs sorted by gate mass descending (hottest first).
    /// This is the content of the ranking CSV, embedded directly.
    pub ranking: &'static [u32],
}

// Pre-computed expert rankings by gate mass (hottest first).
// Generated by: llama-moe-analyze --export-ranking --all-layers
// These are a property of the model weights — compute once, embed forever.

#[rustfmt::skip]
static QWEN3_30B_A3B_RANKING: &[u32] = &[
    0, 26, 41, 69, 104, 70, 81, 89, 7, 21, 105, 75, 8, 78, 82, 5, 115, 16, 59, 32,
    111, 38, 103, 49, 51, 73, 96, 85, 18, 71, 68, 2, 47, 37, 58, 24, 110, 57, 65, 98,
    14, 80, 52, 112, 113, 36, 84, 9, 30, 28, 66, 122, 50, 92, 1, 10, 3, 91, 56, 117,
    87, 17, 64, 34, 25, 94, 33, 86, 102, 74, 120, 31, 4, 45, 13, 61, 99, 93, 107, 46,
    48, 55, 35, 12, 22, 124, 29, 27, 53, 44, 6, 39, 123, 116, 101, 126, 62, 127, 106, 97,
    63, 72, 109, 42, 125, 20, 76, 43, 121, 90, 100, 77, 23, 119, 83, 11, 54, 19, 114, 79,
    108, 40, 67, 88, 60, 95, 118, 15,
];

pub const MODEL_CATALOG: &[CatalogModel] = &[
    // ── Tiny (≤3GB VRAM) ────────────────────────────────────────────
    CatalogModel {
        name: "Qwen3-4B-Q4_K_M",
        file: "Qwen3-4B-Q4_K_M.gguf",
        url: "https://huggingface.co/unsloth/Qwen3-4B-GGUF/resolve/main/Qwen3-4B-Q4_K_M.gguf",
        size: "2.5GB",
        description: "Qwen3 starter, thinking/non-thinking modes",
        draft: Some("Qwen3-0.6B-Q4_K_M"),
        moe: None,
        extra_files: &[],
        mmproj: None,
    },
    CatalogModel {
        name: "Qwen2.5-3B-Instruct-Q4_K_M",
        file: "Qwen2.5-3B-Instruct-Q4_K_M.gguf",
        url: "https://huggingface.co/Qwen/Qwen2.5-3B-Instruct-GGUF/resolve/main/qwen2.5-3b-instruct-q4_k_m.gguf",
        size: "2.1GB",
        description: "Small & fast general chat",
        draft: Some("Qwen2.5-0.5B-Instruct-Q4_K_M"),
        moe: None,
        extra_files: &[],
        mmproj: None,
    },
    CatalogModel {
        name: "Llama-3.2-3B-Instruct-Q4_K_M",
        file: "Llama-3.2-3B-Instruct-Q4_K_M.gguf",
        url: "https://huggingface.co/bartowski/Llama-3.2-3B-Instruct-GGUF/resolve/main/Llama-3.2-3B-Instruct-Q4_K_M.gguf",
        size: "2.0GB",
        description: "Meta Llama 3.2, goose default, good tool calling",
        draft: Some("Llama-3.2-1B-Instruct-Q4_K_M"),
        moe: None,
        extra_files: &[],
        mmproj: None,
    },
    // ── Small (6-8GB VRAM) ──────────────────────────────────────────
    CatalogModel {
        name: "Qwen3-8B-Q4_K_M",
        file: "Qwen3-8B-Q4_K_M.gguf",
        url: "https://huggingface.co/unsloth/Qwen3-8B-GGUF/resolve/main/Qwen3-8B-Q4_K_M.gguf",
        size: "5.0GB",
        description: "Qwen3 mid-tier, strong for its size",
        draft: Some("Qwen3-0.6B-Q4_K_M"),
        moe: None,
        extra_files: &[],
        mmproj: None,
    },
    CatalogModel {
        name: "Qwen2.5-Coder-7B-Instruct-Q4_K_M",
        file: "Qwen2.5-Coder-7B-Instruct-Q4_K_M.gguf",
        url: "https://huggingface.co/Qwen/Qwen2.5-Coder-7B-Instruct-GGUF/resolve/main/qwen2.5-coder-7b-instruct-q4_k_m.gguf",
        size: "4.4GB",
        description: "Code generation & completion",
        draft: Some("Qwen2.5-0.5B-Instruct-Q4_K_M"),
        moe: None,
        extra_files: &[],
        mmproj: None,
    },
    CatalogModel {
        name: "Gemma-3-12B-it-Q4_K_M",
        file: "Gemma-3-12B-it-Q4_K_M.gguf",
        url: "https://huggingface.co/unsloth/gemma-3-12b-it-GGUF/resolve/main/gemma-3-12b-it-Q4_K_M.gguf",
        size: "7.3GB",
        description: "Google Gemma 3 12B, punches above weight",
        draft: Some("Gemma-3-1B-it-Q4_K_M"),
        moe: None,
        extra_files: &[],
        mmproj: None,
    },
    CatalogModel {
        name: "Hermes-2-Pro-Mistral-7B-Q4_K_M",
        file: "Hermes-2-Pro-Mistral-7B-Q4_K_M.gguf",
        url: "https://huggingface.co/bartowski/Hermes-2-Pro-Mistral-7B-GGUF/resolve/main/Hermes-2-Pro-Mistral-7B-Q4_K_M.gguf",
        size: "4.4GB",
        description: "Goose default, strong tool calling for agents",
        draft: None,
        moe: None,
        extra_files: &[],
        mmproj: None,
    },
    // ── Medium (11-17GB VRAM) ───────────────────────────────────────
    CatalogModel {
        name: "Qwen3-14B-Q4_K_M",
        file: "Qwen3-14B-Q4_K_M.gguf",
        url: "https://huggingface.co/unsloth/Qwen3-14B-GGUF/resolve/main/Qwen3-14B-Q4_K_M.gguf",
        size: "9.0GB",
        description: "Qwen3 strong chat, thinking modes",
        draft: Some("Qwen3-0.6B-Q4_K_M"),
        moe: None,
        extra_files: &[],
        mmproj: None,
    },
    CatalogModel {
        name: "Qwen2.5-14B-Instruct-Q4_K_M",
        file: "Qwen2.5-14B-Instruct-Q4_K_M.gguf",
        url: "https://huggingface.co/bartowski/Qwen2.5-14B-Instruct-GGUF/resolve/main/Qwen2.5-14B-Instruct-Q4_K_M.gguf",
        size: "9.0GB",
        description: "Solid general chat",
        draft: Some("Qwen2.5-0.5B-Instruct-Q4_K_M"),
        moe: None,
        extra_files: &[],
        mmproj: None,
    },
    CatalogModel {
        name: "Qwen2.5-Coder-14B-Instruct-Q4_K_M",
        file: "Qwen2.5-Coder-14B-Instruct-Q4_K_M.gguf",
        url: "https://huggingface.co/bartowski/Qwen2.5-Coder-14B-Instruct-GGUF/resolve/main/Qwen2.5-Coder-14B-Instruct-Q4_K_M.gguf",
        size: "9.0GB",
        description: "Strong code gen, fills gap between 7B and 32B",
        draft: Some("Qwen2.5-0.5B-Instruct-Q4_K_M"),
        moe: None,
        extra_files: &[],
        mmproj: None,
    },
    CatalogModel {
        name: "DeepSeek-R1-Distill-Qwen-14B-Q4_K_M",
        file: "DeepSeek-R1-Distill-Qwen-14B-Q4_K_M.gguf",
        url: "https://huggingface.co/unsloth/DeepSeek-R1-Distill-Qwen-14B-GGUF/resolve/main/DeepSeek-R1-Distill-Qwen-14B-Q4_K_M.gguf",
        size: "9.0GB",
        description: "DeepSeek R1 reasoning distilled into Qwen 14B",
        draft: Some("Qwen2.5-0.5B-Instruct-Q4_K_M"),
        moe: None,
        extra_files: &[],
        mmproj: None,
    },
    CatalogModel {
        name: "Devstral-Small-2505-Q4_K_M",
        file: "Devstral-Small-2505-Q4_K_M.gguf",
        url: "https://huggingface.co/unsloth/Devstral-Small-2505-GGUF/resolve/main/Devstral-Small-2505-Q4_K_M.gguf",
        size: "14.3GB",
        description: "Mistral agentic coding, tool use",
        draft: None,
        moe: None,
        extra_files: &[],
        mmproj: None,
    },
    CatalogModel {
        name: "Mistral-Small-3.1-24B-Instruct-Q4_K_M",
        file: "Mistral-Small-3.1-24B-Instruct-2503-Q4_K_M.gguf",
        url: "https://huggingface.co/unsloth/Mistral-Small-3.1-24B-Instruct-2503-GGUF/resolve/main/Mistral-Small-3.1-24B-Instruct-2503-Q4_K_M.gguf",
        size: "14.3GB",
        description: "Mistral general chat, good tool calling",
        draft: None,
        moe: None,
        extra_files: &[],
        mmproj: None,
    },
    // ── Large (20-24GB VRAM) ────────────────────────────────────────
    CatalogModel {
        name: "GLM-4.7-Flash-Q4_K_M",
        file: "GLM-4.7-Flash-Q4_K_M.gguf",
        url: "https://huggingface.co/unsloth/GLM-4.7-Flash-GGUF/resolve/main/GLM-4.7-Flash-Q4_K_M.gguf",
        size: "18GB",
        description: "MoE 30B/3B active, 64 experts top-4, fast inference, tool calling",
        draft: None,
        moe: Some(MoeConfig {
            n_expert: 64,
            n_expert_used: 4,
            min_experts_per_node: 24,
            ranking: &[], // no pre-baked ranking — uses GGUF auto-detect + fallback
        }),
        extra_files: &[],
        mmproj: None,
    },
    CatalogModel {
        name: "Qwen3-30B-A3B-Q4_K_M",
        file: "Qwen3-30B-A3B-Q4_K_M.gguf",
        url: "https://huggingface.co/unsloth/Qwen3-30B-A3B-GGUF/resolve/main/Qwen3-30B-A3B-Q4_K_M.gguf",
        size: "17.3GB",
        description: "MoE general chat, 128 experts top-8, thinking/non-thinking",
        draft: Some("Qwen3-0.6B-Q4_K_M"),
        moe: Some(MoeConfig {
            n_expert: 128,
            n_expert_used: 8,
            min_experts_per_node: 46,
            ranking: QWEN3_30B_A3B_RANKING, // same arch as Coder variant
        }),
        extra_files: &[],
        mmproj: None,
    },
    CatalogModel {
        name: "Qwen3-Coder-30B-A3B-Instruct-Q4_K_M",
        file: "Qwen3-Coder-30B-A3B-Instruct-Q4_K_M.gguf",
        url: "https://huggingface.co/unsloth/Qwen3-Coder-30B-A3B-Instruct-GGUF/resolve/main/Qwen3-Coder-30B-A3B-Instruct-Q4_K_M.gguf",
        size: "18.6GB",
        description: "MoE agentic coding, tool use, 128 experts top-8",
        draft: Some("Qwen3-0.6B-Q4_K_M"),
        moe: Some(MoeConfig {
            n_expert: 128,
            n_expert_used: 8,
            min_experts_per_node: 46,
            ranking: QWEN3_30B_A3B_RANKING, // same arch as Qwen3-30B-A3B
        }),
        extra_files: &[],
        mmproj: None,
    },
    CatalogModel {
        name: "GLM-4-32B-0414-Q4_K_M",
        file: "GLM-4-32B-0414-Q4_K_M.gguf",
        url: "https://huggingface.co/unsloth/GLM-4-32B-0414-GGUF/resolve/main/GLM-4-32B-0414-Q4_K_M.gguf",
        size: "19.7GB",
        description: "Strong 32B, good tool calling",
        draft: None,
        moe: None,
        extra_files: &[],
        mmproj: None,
    },
    CatalogModel {
        name: "Qwen3-32B-Q4_K_M",
        file: "Qwen3-32B-Q4_K_M.gguf",
        url: "https://huggingface.co/unsloth/Qwen3-32B-GGUF/resolve/main/Qwen3-32B-Q4_K_M.gguf",
        size: "19.8GB",
        description: "Best Qwen3 dense, thinking/non-thinking modes",
        draft: Some("Qwen3-0.6B-Q4_K_M"),
        moe: None,
        extra_files: &[],
        mmproj: None,
    },
    CatalogModel {
        name: "DeepSeek-R1-Distill-Qwen-32B-Q4_K_M",
        file: "DeepSeek-R1-Distill-Qwen-32B-Q4_K_M.gguf",
        url: "https://huggingface.co/unsloth/DeepSeek-R1-Distill-Qwen-32B-GGUF/resolve/main/DeepSeek-R1-Distill-Qwen-32B-Q4_K_M.gguf",
        size: "19.9GB",
        description: "DeepSeek R1 reasoning distilled into Qwen 32B",
        draft: Some("Qwen2.5-0.5B-Instruct-Q4_K_M"),
        moe: None,
        extra_files: &[],
        mmproj: None,
    },
    CatalogModel {
        name: "Qwen2.5-32B-Instruct-Q4_K_M",
        file: "Qwen2.5-32B-Instruct-Q4_K_M.gguf",
        url: "https://huggingface.co/bartowski/Qwen2.5-32B-Instruct-GGUF/resolve/main/Qwen2.5-32B-Instruct-Q4_K_M.gguf",
        size: "20GB",
        description: "Proven general chat",
        draft: Some("Qwen2.5-0.5B-Instruct-Q4_K_M"),
        moe: None,
        extra_files: &[],
        mmproj: None,
    },
    CatalogModel {
        name: "Qwen2.5-Coder-32B-Instruct-Q4_K_M",
        file: "Qwen2.5-Coder-32B-Instruct-Q4_K_M.gguf",
        url: "https://huggingface.co/Qwen/Qwen2.5-Coder-32B-Instruct-GGUF/resolve/main/qwen2.5-coder-32b-instruct-q4_k_m.gguf",
        size: "20GB",
        description: "Top-tier code gen, matches GPT-4o on code",
        draft: Some("Qwen2.5-0.5B-Instruct-Q4_K_M"),
        moe: None,
        extra_files: &[],
        mmproj: None,
    },
    CatalogModel {
        name: "Llama-4-Scout-Q4_K_M",
        file: "Llama-4-Scout-4bit-Q4_K_M.gguf",
        url: "https://huggingface.co/glogwa68/Llama-4-scout-GGUF/resolve/main/Llama-4-Scout-4bit-Q4_K_M.gguf",
        size: "22.5GB",
        description: "MoE 109B/17B active, 16 experts top-1, Meta latest, tool calling",
        draft: None,
        moe: Some(MoeConfig {
            n_expert: 16,
            n_expert_used: 1,
            min_experts_per_node: 6,
            ranking: &[], // no pre-baked ranking — uses GGUF auto-detect
        }),
        extra_files: &[],
        mmproj: None,
    },
    CatalogModel {
        name: "Gemma-3-27B-it-Q4_K_M",
        file: "Gemma-3-27B-it-Q4_K_M.gguf",
        url: "https://huggingface.co/bartowski/google_gemma-3-27b-it-GGUF/resolve/main/google_gemma-3-27b-it-Q4_K_M.gguf",
        size: "17GB",
        description: "Google Gemma 3 27B, strong reasoning",
        draft: Some("Gemma-3-1B-it-Q4_K_M"),
        moe: None,
        extra_files: &[],
        mmproj: None,
    },
    CatalogModel {
        name: "Qwen3.5-27B-Q4_K_M",
        file: "Qwen3.5-27B-Q4_K_M.gguf",
        url: "https://registry.ollama.ai/v2/library/qwen3.5/blobs/sha256:d4b8b4f4c350f5d322dc8235175eeae02d32c6f3fd70bdb9ea481e3abb7d7fc4",
        size: "17GB",
        description: "Qwen3.5 27B, vision + text, strong reasoning and coding",
        draft: Some("Qwen3-0.6B-Q4_K_M"),
        moe: None,
        extra_files: &[],
        mmproj: Some(("Qwen3.5-27B-mmproj-BF16.gguf", "https://huggingface.co/unsloth/Qwen3.5-27B-GGUF/resolve/main/mmproj-BF16.gguf")),
    },
    // ── Large (40GB+ VRAM) ────────────────────────────────────────
    CatalogModel {
        name: "Qwen3-Coder-Next-Q4_K_M",
        file: "Qwen3-Coder-Next-Q4_K_M-00001-of-00004.gguf",
        url: "https://huggingface.co/Qwen/Qwen3-Coder-Next-GGUF/resolve/main/Qwen3-Coder-Next-Q4_K_M/Qwen3-Coder-Next-Q4_K_M-00001-of-00004.gguf",
        size: "48GB",
        description: "Qwen3 Coder Next ~85B dense, frontier coding model",
        draft: None,
        moe: None,
        extra_files: &[
            ("Qwen3-Coder-Next-Q4_K_M-00002-of-00004.gguf", "https://huggingface.co/Qwen/Qwen3-Coder-Next-GGUF/resolve/main/Qwen3-Coder-Next-Q4_K_M/Qwen3-Coder-Next-Q4_K_M-00002-of-00004.gguf"),
            ("Qwen3-Coder-Next-Q4_K_M-00003-of-00004.gguf", "https://huggingface.co/Qwen/Qwen3-Coder-Next-GGUF/resolve/main/Qwen3-Coder-Next-Q4_K_M/Qwen3-Coder-Next-Q4_K_M-00003-of-00004.gguf"),
            ("Qwen3-Coder-Next-Q4_K_M-00004-of-00004.gguf", "https://huggingface.co/Qwen/Qwen3-Coder-Next-GGUF/resolve/main/Qwen3-Coder-Next-Q4_K_M/Qwen3-Coder-Next-Q4_K_M-00004-of-00004.gguf"),
        ],
        mmproj: None,
    },
    CatalogModel {
        name: "Llama-3.3-70B-Instruct-Q4_K_M",
        file: "Llama-3.3-70B-Instruct-Q4_K_M.gguf",
        url: "https://registry.ollama.ai/v2/library/llama3.3/blobs/sha256:4824460d29f2058aaf6e1118a63a7a197a09bed509f0e7d4e2efb1ee273b447d",
        size: "43GB",
        description: "Meta Llama 3.3 70B, strong all-around",
        draft: Some("Llama-3.2-1B-Instruct-Q4_K_M"),
        moe: None,
        extra_files: &[],
        mmproj: None,
    },
    CatalogModel {
        name: "Qwen2.5-72B-Instruct-Q4_K_M",
        file: "Qwen2.5-72B-Instruct-Q4_K_M.gguf",
        url: "https://registry.ollama.ai/v2/library/qwen2.5/blobs/sha256:6e7fdda508e91cb0f63de5c15ff79ac63a1584ccafd751c07ca12b7f442101b8",
        size: "47GB",
        description: "Flagship Qwen2.5, great tensor split showcase",
        draft: Some("Qwen2.5-0.5B-Instruct-Q4_K_M"),
        moe: None,
        extra_files: &[],
        mmproj: None,
    },
    CatalogModel {
        name: "DeepSeek-R1-Distill-70B-Q4_K_M",
        file: "DeepSeek-R1-Distill-70B-Q4_K_M.gguf",
        url: "https://registry.ollama.ai/v2/library/deepseek-r1/blobs/sha256:4cd576d9aa16961244012223abf01445567b061f1814b57dfef699e4cf8df339",
        size: "43GB",
        description: "DeepSeek R1 distilled to 70B (Qwen2.5-based), strong reasoning",
        draft: None,
        moe: None,
        extra_files: &[],
        mmproj: None,
    },
    CatalogModel {
        name: "Mixtral-8x22B-Instruct-Q4_K_M",
        file: "Mixtral-8x22B-Instruct-Q4_K_M.gguf",
        url: "https://registry.ollama.ai/v2/library/mixtral/blobs/sha256:f3329ad0c787f4f73cab99e8c877bb76403060561dd0caa318127683c87bbcb4",
        size: "86GB",
        description: "Mixtral 8x22B MoE, 8 experts top-2",
        draft: None,
        moe: Some(MoeConfig {
            n_expert: 8,
            n_expert_used: 2,
            min_experts_per_node: 4,
            ranking: &[],
        }),
        extra_files: &[],
        mmproj: None,
    },
    // ── XXL (100GB+ VRAM) ─────────────────────────────────────────
    CatalogModel {
        name: "Qwen3-235B-A22B-Q4_K_M",
        file: "Qwen3-235B-A22B-Q4_K_M.gguf",
        url: "https://registry.ollama.ai/v2/library/qwen3/blobs/sha256:aeacdadecbed8a07e42026d1a1d3cd30715bb2994ebe4e4ca4009e1a4abe8d5d",
        size: "142GB",
        description: "Qwen3 235B MoE A22B active, 128 experts top-8",
        draft: None,
        moe: Some(MoeConfig {
            n_expert: 128,
            n_expert_used: 8,
            min_experts_per_node: 46,
            ranking: &[],
        }),
        extra_files: &[],
        mmproj: None,
    },
    CatalogModel {
        name: "Llama-3.1-405B-Instruct-Q2_K",
        file: "Llama-3.1-405B-Instruct-Q2_K.gguf",
        url: "https://registry.ollama.ai/v2/library/llama3.1/blobs/sha256:e7e1972e5b13caead8a8dd9c94f4a0dec59ac2d9dd52e0cd1c067e6077eb4677",
        size: "149GB",
        description: "Llama 3.1 405B Instruct Q2_K, largest dense model",
        draft: None,
        moe: None,
        extra_files: &[],
        mmproj: None,
    },
    // ── XXL (100GB+ VRAM, split GGUF) ─────────────────────────────
    CatalogModel {
        name: "MiniMax-M2.5-Q4_K_M",
        file: "MiniMax-M2.5-Q4_K_M-00001-of-00004.gguf",
        url: "https://huggingface.co/unsloth/MiniMax-M2.5-GGUF/resolve/main/Q4_K_M/MiniMax-M2.5-Q4_K_M-00001-of-00004.gguf",
        size: "138GB",
        description: "MiniMax-M2.5 MoE 456B/46B active, 256 experts top-8, Q4_K_M",
        draft: None,
        moe: Some(MoeConfig {
            n_expert: 256,
            n_expert_used: 8,
            min_experts_per_node: 96,
            ranking: &[],
        }),
        extra_files: &[
            ("MiniMax-M2.5-Q4_K_M-00002-of-00004.gguf", "https://huggingface.co/unsloth/MiniMax-M2.5-GGUF/resolve/main/Q4_K_M/MiniMax-M2.5-Q4_K_M-00002-of-00004.gguf"),
            ("MiniMax-M2.5-Q4_K_M-00003-of-00004.gguf", "https://huggingface.co/unsloth/MiniMax-M2.5-GGUF/resolve/main/Q4_K_M/MiniMax-M2.5-Q4_K_M-00003-of-00004.gguf"),
            ("MiniMax-M2.5-Q4_K_M-00004-of-00004.gguf", "https://huggingface.co/unsloth/MiniMax-M2.5-GGUF/resolve/main/Q4_K_M/MiniMax-M2.5-Q4_K_M-00004-of-00004.gguf"),
        ],
        mmproj: None,
    },
    // ── Vision models ───────────────────────────────────────────────
    CatalogModel {
        name: "Qwen3.5-0.8B-Vision-Q4_K_M",
        file: "Qwen3.5-0.8B-Q4_K_M.gguf",
        url: "https://huggingface.co/unsloth/Qwen3.5-0.8B-GGUF/resolve/main/Qwen3.5-0.8B-Q4_K_M.gguf",
        size: "508MB",
        description: "Tiny vision model, OCR, screenshots, runs anywhere",
        draft: None,
        moe: None,
        extra_files: &[],
        mmproj: Some(("Qwen3.5-0.8B-mmproj-BF16.gguf", "https://huggingface.co/unsloth/Qwen3.5-0.8B-GGUF/resolve/main/mmproj-BF16.gguf")),
    },
    CatalogModel {
        name: "Qwen3.5-4B-Vision-Q4_K_M",
        file: "Qwen3.5-4B-Q4_K_M.gguf",
        url: "https://huggingface.co/unsloth/Qwen3.5-4B-GGUF/resolve/main/Qwen3.5-4B-Q4_K_M.gguf",
        size: "2.7GB",
        description: "Small vision model, good quality/size balance",
        draft: None,
        moe: None,
        extra_files: &[],
        mmproj: Some(("Qwen3.5-4B-mmproj-BF16.gguf", "https://huggingface.co/unsloth/Qwen3.5-4B-GGUF/resolve/main/mmproj-BF16.gguf")),
    },
    CatalogModel {
        name: "Qwen3.5-9B-Vision-Q4_K_M",
        file: "Qwen3.5-9B-Q4_K_M.gguf",
        url: "https://huggingface.co/unsloth/Qwen3.5-9B-GGUF/resolve/main/Qwen3.5-9B-Q4_K_M.gguf",
        size: "5.8GB",
        description: "Vision + text, replaces Qwen3-8B with image understanding",
        draft: None,
        moe: None,
        extra_files: &[],
        mmproj: Some(("Qwen3.5-9B-mmproj-BF16.gguf", "https://huggingface.co/unsloth/Qwen3.5-9B-GGUF/resolve/main/mmproj-BF16.gguf")),
    },
    // ── Draft models ────────────────────────────────────────────────
    CatalogModel {
        name: "Qwen2.5-0.5B-Instruct-Q4_K_M",
        file: "Qwen2.5-0.5B-Instruct-Q4_K_M.gguf",
        url: "https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct-GGUF/resolve/main/qwen2.5-0.5b-instruct-q4_k_m.gguf",
        size: "491MB",
        description: "Draft for Qwen2.5 and DeepSeek-R1-Distill models",
        draft: None,
        moe: None,
        extra_files: &[],
        mmproj: None,
    },
    CatalogModel {
        name: "Qwen3-0.6B-Q4_K_M",
        file: "Qwen3-0.6B-Q4_K_M.gguf",
        url: "https://huggingface.co/unsloth/Qwen3-0.6B-GGUF/resolve/main/Qwen3-0.6B-Q4_K_M.gguf",
        size: "397MB",
        description: "Draft for Qwen3 models",
        draft: None,
        moe: None,
        extra_files: &[],
        mmproj: None,
    },
    CatalogModel {
        name: "Llama-3.2-1B-Instruct-Q4_K_M",
        file: "Llama-3.2-1B-Instruct-Q4_K_M.gguf",
        url: "https://huggingface.co/bartowski/Llama-3.2-1B-Instruct-GGUF/resolve/main/Llama-3.2-1B-Instruct-Q4_K_M.gguf",
        size: "760MB",
        description: "Draft for Llama 3.x and Llama 4 models",
        draft: None,
        moe: None,
        extra_files: &[],
        mmproj: None,
    },
    CatalogModel {
        name: "Gemma-3-1B-it-Q4_K_M",
        file: "Gemma-3-1B-it-Q4_K_M.gguf",
        url: "https://huggingface.co/bartowski/google_gemma-3-1b-it-GGUF/resolve/main/google_gemma-3-1b-it-Q4_K_M.gguf",
        size: "780MB",
        description: "Draft for Gemma 3 models",
        draft: None,
        moe: None,
        extra_files: &[],
        mmproj: None,
    },
];

/// Get the models directory (~/.models/)
pub fn models_dir() -> PathBuf {
    dirs::home_dir()
        .unwrap_or_else(|| PathBuf::from("."))
        .join(".models")
}

/// Find a catalog model by name (case-insensitive partial match)
/// Parse a size string like "20GB", "4.4GB", "491MB" into GB as f64.
pub fn parse_size_gb(s: &str) -> f64 {
    let s = s.trim();
    if let Some(gb) = s.strip_suffix("GB") {
        gb.trim().parse().unwrap_or(0.0)
    } else if let Some(mb) = s.strip_suffix("MB") {
        mb.trim().parse::<f64>().unwrap_or(0.0) / 1000.0
    } else {
        0.0
    }
}

pub fn find_model(query: &str) -> Option<&'static CatalogModel> {
    let q = query.to_lowercase();
    MODEL_CATALOG
        .iter()
        .find(|m| m.name.to_lowercase() == q)
        .or_else(|| {
            MODEL_CATALOG
                .iter()
                .find(|m| m.name.to_lowercase().contains(&q))
        })
}

/// Download a model to ~/.models/ with resume support.
/// Returns the path to the primary downloaded file.
/// For split GGUFs (extra_files), downloads all parts to the same directory.
pub async fn download_model(model: &CatalogModel) -> Result<PathBuf> {
    let dir = models_dir();
    tokio::fs::create_dir_all(&dir).await?;
    let dest = dir.join(model.file);

    // Collect all files to download: primary + extra splits + mmproj
    let mut files: Vec<(&str, &str)> = vec![(model.file, model.url)];
    for (f, u) in model.extra_files {
        files.push((f, u));
    }
    if let Some((f, u)) = &model.mmproj {
        files.push((f, u));
    }

    let mut all_present = true;
    let mut total_size: u64 = 0;
    for (file, _) in &files {
        let path = dir.join(file);
        let size = tokio::fs::metadata(&path)
            .await
            .map(|m| m.len())
            .unwrap_or(0);
        if size < 1_000_000 {
            all_present = false;
            break;
        }
        total_size += size;
    }

    if all_present {
        eprintln!(
            "✅ {} already exists ({:.1}GB, {} file{})",
            model.name,
            total_size as f64 / 1e9,
            files.len(),
            if files.len() > 1 { "s" } else { "" },
        );
        return Ok(dest);
    }

    eprintln!("📥 Downloading {} ({})...", model.name, model.size);

    // Collect files that still need downloading
    let mut needed: Vec<(String, String)> = Vec::new();
    for (file, url) in &files {
        let path = dir.join(file);
        if path.exists() {
            let size = tokio::fs::metadata(&path)
                .await
                .map(|m| m.len())
                .unwrap_or(0);
            if size > 1_000_000 {
                eprintln!("  ✅ {file} already exists ({:.1}GB)", size as f64 / 1e9);
                continue;
            }
        }
        needed.push((file.to_string(), url.to_string()));
    }

    if needed.len() > 1 {
        // Parallel download of split files
        eprintln!("  ⚡ Downloading {} files in parallel...", needed.len());
        let total = needed.len();
        let completed = std::sync::Arc::new(std::sync::atomic::AtomicUsize::new(0));
        let mut handles = Vec::new();
        for (file, url) in needed {
            let path = dir.join(&file);
            let completed = completed.clone();
            handles.push(tokio::spawn(async move {
                download_with_resume(&path, &url).await?;
                let done = completed.fetch_add(1, std::sync::atomic::Ordering::Relaxed) + 1;
                eprintln!("  ✅ {file} [{done}/{total}]");
                Ok::<(), anyhow::Error>(())
            }));
        }
        for handle in handles {
            handle.await??;
        }
    } else if let Some((file, url)) = needed.into_iter().next() {
        // Single file — just download it
        let path = dir.join(&file);
        download_with_resume(&path, &url).await?;
    }

    eprintln!("✅ Downloaded {} to {}", model.name, dir.display());
    Ok(dest)
}

/// Download any URL to a destination path with resume support.
pub async fn download_url(url: &str, dest: &Path) -> Result<()> {
    download_with_resume(dest, url).await
}

/// Download a HuggingFace GGUF URL, auto-detecting split files (-00001-of-NNNNN.gguf).
/// If the filename matches the split pattern, discovers and downloads all parts in parallel.
/// Returns the path to the first part (or the single file).
pub async fn download_hf_split_gguf(url: &str, filename: &str) -> Result<PathBuf> {
    let dir = models_dir();
    tokio::fs::create_dir_all(&dir).await?;

    let re = regex_lite::Regex::new(r"-00001-of-(\d{5})\.gguf$").unwrap();
    if let Some(caps) = re.captures(filename) {
        let n: u32 = caps[1].parse()?;
        eprintln!("📥 Detected split GGUF: {n} parts");

        // Build list of (part_filename, part_url) for all parts
        let mut files: Vec<(String, String)> = Vec::new();
        for i in 1..=n {
            let part_filename = filename.replace("-00001-of-", &format!("-{i:05}-of-"));
            let part_url = url.replace("-00001-of-", &format!("-{i:05}-of-"));
            files.push((part_filename, part_url));
        }

        // Filter to parts that still need downloading
        let mut needed: Vec<(String, String)> = Vec::new();
        for (f, u) in &files {
            let path = dir.join(f);
            if path.exists() {
                let size = tokio::fs::metadata(&path)
                    .await
                    .map(|m| m.len())
                    .unwrap_or(0);
                if size > 1_000_000 {
                    eprintln!("  ✅ {f} already exists ({:.1}GB)", size as f64 / 1e9);
                    continue;
                }
            }
            needed.push((f.clone(), u.clone()));
        }

        if !needed.is_empty() {
            eprintln!("  ⚡ Downloading {} file(s) in parallel...", needed.len());
            let total = needed.len();
            let completed = std::sync::Arc::new(std::sync::atomic::AtomicUsize::new(0));
            let mut handles = Vec::new();
            for (file, url) in needed {
                let path = dir.join(&file);
                let completed = completed.clone();
                handles.push(tokio::spawn(async move {
                    download_with_resume(&path, &url).await?;
                    let done = completed.fetch_add(1, std::sync::atomic::Ordering::Relaxed) + 1;
                    eprintln!("  ✅ {file} [{done}/{total}]");
                    Ok::<(), anyhow::Error>(())
                }));
            }
            for handle in handles {
                handle.await??;
            }
        }

        return Ok(dir.join(filename));
    }

    // Not a split file — single download
    let dest = dir.join(filename);
    if dest.exists() {
        let size = tokio::fs::metadata(&dest).await?.len();
        if size > 1_000_000 {
            eprintln!(
                "✅ {} already exists ({:.1}GB)",
                filename,
                size as f64 / 1e9
            );
            return Ok(dest);
        }
    }
    eprintln!("📥 Downloading {filename}...");
    download_with_resume(&dest, url).await?;
    Ok(dest)
}

/// Download with resume support and retries using reqwest.
async fn download_with_resume(dest: &Path, url: &str) -> Result<()> {
    use tokio_stream::StreamExt;

    let tmp = dest.with_extension("gguf.part");
    let client = reqwest::Client::builder()
        .timeout(std::time::Duration::from_secs(3600)) // 1h overall timeout
        .connect_timeout(std::time::Duration::from_secs(30))
        .build()?;

    let mut attempt: u64 = 0;
    loop {
        attempt += 1;
        // Check how much we already have (for resume)
        let existing_bytes = if tmp.exists() {
            tokio::fs::metadata(&tmp).await?.len()
        } else {
            0
        };

        if attempt <= 3 || attempt % 10 == 0 {
            eprintln!(
                "  attempt {attempt}{}...",
                if existing_bytes > 0 {
                    format!(" (resuming from {:.1}MB)", existing_bytes as f64 / 1e6)
                } else {
                    String::new()
                }
            );
        }

        let mut request = client.get(url);
        if existing_bytes > 0 {
            request = request.header("Range", format!("bytes={existing_bytes}-"));
        }

        // Exponential backoff: 3s, 6s, 12s, ... capped at 60s
        let backoff_secs = std::cmp::min(3 * (1u64 << (attempt - 1).min(4)), 60);

        let response = match request.send().await {
            Ok(r) => r,
            Err(e) => {
                eprintln!("  connection failed: {e}");
                eprintln!("  retrying in {backoff_secs}s...");
                tokio::time::sleep(std::time::Duration::from_secs(backoff_secs)).await;
                continue;
            }
        };

        let status = response.status();
        if !status.is_success() && status != reqwest::StatusCode::PARTIAL_CONTENT {
            // If server doesn't support resume (416 Range Not Satisfiable), start fresh
            if status == reqwest::StatusCode::RANGE_NOT_SATISFIABLE {
                let _ = tokio::fs::remove_file(&tmp).await;
                eprintln!("  server rejected resume, starting fresh...");
                continue;
            }
            eprintln!("  HTTP {status}, retrying in {backoff_secs}s...");
            tokio::time::sleep(std::time::Duration::from_secs(backoff_secs)).await;
            continue;
        }

        // Total size from Content-Length (or Content-Range)
        let total_bytes = if status == reqwest::StatusCode::PARTIAL_CONTENT {
            // Content-Range: bytes 1234-5678/9999
            response
                .headers()
                .get("content-range")
                .and_then(|v| v.to_str().ok())
                .and_then(|s| s.rsplit('/').next())
                .and_then(|s| s.parse::<u64>().ok())
        } else {
            response.content_length().map(|cl| cl + existing_bytes)
        };

        // On first successful response, check disk space
        if attempt == 1 || existing_bytes == 0 {
            if let Some(total) = total_bytes {
                let remaining = total.saturating_sub(existing_bytes);
                if let Some(free) = free_disk_space(dest) {
                    // Need remaining bytes + 1GB headroom
                    let needed = remaining + 1_000_000_000;
                    if free < needed {
                        anyhow::bail!(
                            "Not enough disk space: need {:.1}GB but only {:.1}GB free on {}",
                            needed as f64 / 1e9,
                            free as f64 / 1e9,
                            dest.parent().unwrap_or(dest).display()
                        );
                    }
                }
            }
        }

        // Open file for append (resume) or create
        let mut file = tokio::fs::OpenOptions::new()
            .create(true)
            .append(true)
            .open(&tmp)
            .await
            .context("Failed to open temp file")?;

        let mut stream = response.bytes_stream();
        let mut downloaded = existing_bytes;
        let mut last_progress = std::time::Instant::now();

        // Print initial progress
        print_progress(downloaded, total_bytes);

        // Reset backoff on successful data receipt
        let mut got_data = false;

        loop {
            match stream.next().await {
                Some(Ok(chunk)) => {
                    file.write_all(&chunk)
                        .await
                        .context("Failed to write chunk")?;
                    downloaded += chunk.len() as u64;
                    got_data = true;

                    // Update progress every 500ms
                    if last_progress.elapsed() >= std::time::Duration::from_millis(500) {
                        print_progress(downloaded, total_bytes);
                        last_progress = std::time::Instant::now();
                    }
                }
                Some(Err(e)) => {
                    file.flush().await.ok();
                    eprint!("\r");
                    eprintln!(
                        "  download interrupted at {:.1}MB: {e}",
                        downloaded as f64 / 1e6
                    );
                    // If we got data, reset attempt counter (connection was working)
                    if got_data {
                        attempt = 0;
                    }
                    let retry_secs = std::cmp::min(3 * (1u64 << attempt.min(4)), 60);
                    eprintln!("  retrying in {retry_secs}s (will resume)...");
                    tokio::time::sleep(std::time::Duration::from_secs(retry_secs)).await;
                    break;
                }
                None => {
                    // Stream complete
                    file.flush().await?;
                    eprint!("\r");
                    print_progress(downloaded, total_bytes);
                    eprintln!();
                    tokio::fs::rename(&tmp, dest)
                        .await
                        .context("Failed to move downloaded file")?;
                    return Ok(());
                }
            }
        }
    }
}

/// Check free disk space on the filesystem containing `path`.
/// Returns None if the check fails (e.g. path doesn't exist yet).
fn free_disk_space(path: &Path) -> Option<u64> {
    // Walk up to find an existing directory for statvfs
    let mut check = path.to_path_buf();
    loop {
        if check.exists() {
            break;
        }
        if !check.pop() {
            return None;
        }
    }
    #[cfg(unix)]
    {
        use std::os::unix::ffi::OsStrExt;
        let c_path = std::ffi::CString::new(check.as_os_str().as_bytes()).ok()?;
        let mut stat: libc::statvfs = unsafe { std::mem::zeroed() };
        let ret = unsafe { libc::statvfs(c_path.as_ptr(), &mut stat) };
        if ret == 0 {
            // f_bavail = blocks available to unprivileged users
            Some(stat.f_bavail as u64 * stat.f_frsize as u64)
        } else {
            None
        }
    }
    #[cfg(not(unix))]
    {
        None
    }
}

fn print_progress(downloaded: u64, total: Option<u64>) {
    if let Some(total) = total {
        let pct = (downloaded as f64 / total as f64) * 100.0;
        let downloaded_mb = downloaded as f64 / 1e6;
        let total_mb = total as f64 / 1e6;
        eprint!("\r  {:.1}/{:.1}MB ({:.1}%)", downloaded_mb, total_mb, pct);
    } else {
        eprint!("\r  {:.1}MB", downloaded as f64 / 1e6);
    }
}

/// List available models
pub fn list_models() {
    eprintln!("Available models:");
    eprintln!();
    for m in MODEL_CATALOG {
        let draft_info = if let Some(d) = m.draft {
            format!(" (draft: {})", d)
        } else {
            String::new()
        };
        eprintln!(
            "  {:40} {:>6}  {}{}",
            m.name, m.size, m.description, draft_info
        );
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_free_disk_space() {
        let path = std::env::temp_dir().join("test_file.gguf");
        let free = free_disk_space(&path);

        #[cfg(unix)]
        {
            assert!(
                free.is_some(),
                "should get free space for {}",
                path.display()
            );
            let bytes = free.unwrap();
            assert!(bytes > 1_000_000_000, "should have >1GB free, got {bytes}");
        }

        #[cfg(not(unix))]
        {
            assert!(free.is_none(), "non-unix builds should skip statvfs checks");
        }
    }

    #[test]
    fn test_split_gguf_detection() {
        let re = regex_lite::Regex::new(r"-00001-of-(\d{5})\.gguf$").unwrap();

        // Should match split GGUFs
        let caps = re.captures("Model-Q4_K_M-00001-of-00004.gguf");
        assert!(caps.is_some());
        assert_eq!(&caps.unwrap()[1], "00004");

        let caps = re.captures("Qwen3-Coder-Next-Q4_K_M-00001-of-00004.gguf");
        assert!(caps.is_some());

        let caps = re.captures("MiniMax-M2.5-Q4_K_M-00001-of-00004.gguf");
        assert!(caps.is_some());

        // Should NOT match non-split or other parts
        assert!(re.captures("Model-Q4_K_M.gguf").is_none());
        assert!(re.captures("Model-Q4_K_M-00002-of-00004.gguf").is_none());
        assert!(re.captures("Model-Q4_K_M-00001-of-00004.bin").is_none());
    }

    #[test]
    fn test_split_url_generation() {
        let filename = "Model-Q4_K_M-00001-of-00003.gguf";
        let url = "https://huggingface.co/org/repo/resolve/main/Model-Q4_K_M-00001-of-00003.gguf";

        let mut files = Vec::new();
        for i in 1..=3u32 {
            let part_filename = filename.replace("-00001-of-", &format!("-{i:05}-of-"));
            let part_url = url.replace("-00001-of-", &format!("-{i:05}-of-"));
            files.push((part_filename, part_url));
        }

        assert_eq!(files.len(), 3);
        assert_eq!(files[0].0, "Model-Q4_K_M-00001-of-00003.gguf");
        assert_eq!(files[1].0, "Model-Q4_K_M-00002-of-00003.gguf");
        assert_eq!(files[2].0, "Model-Q4_K_M-00003-of-00003.gguf");
        assert!(files[0].1.contains("-00001-of-"));
        assert!(files[1].1.contains("-00002-of-"));
        assert!(files[2].1.contains("-00003-of-"));
    }
}
